### ISSUE TITLE
check-postgres-replication.rb: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by chris-edwards-pub** [sensu-plugins/sensu-plugins-postgres#70] opened 2018-11-21 18:58 UTC
I ran the following and i'm getting an error.  This is on a Centos 7 box.

```
check-postgres-replication.rb -m localhost -s localhost -u sensumon -p password
Check failed to run: undefined method `split' for nil:NilClass, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-postgres-2.2.2/lib/sensu-plugins-postgres/pgutil.rb:10:in `compute_lag'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-postgres-2.2.2/bin/check-postgres-replication.rb:141:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

Thanks,

Chris

**Comment by phumpal** [comment] 2018-12-17 05:00
Is it possible the values are empty?

I'm slightly confused; the check appears to be pointed to localhost and the default port for both master and slave? Is this not the case?

**Comment by sys-ops** [comment] 2019-03-12 14:08
check-postgres-replication.rb
```
   133      slave = if check_vsn_newer_than_postgres9(conn_slave)
   134                conn_slave.exec('SELECT pg_last_xlog_receive_location()').getvalue(0, 0)
   135              else
   136                conn_slave.exec('SELECT pg_last_wal_replay_lsn()').getvalue(0, 0)
   137              end
   138      conn_slave.close`
```
This is what I got on the slave:
```
 postgres=# SELECT pg_last_xlog_receive_location();
  pg_last_xlog_receive_location 
 -------------------------------
 
 (1 row)
```
The row is empty, hence in pgutil.rb
```
   14      s_segment, s_offset = slave.split('/')
```
calls **undefined method `split' for nil:NilClass**

**Comment by phumpal** [comment] 2019-03-12 19:47
> calls undefined method `split' for nil:NilClass

Better error handling would be nice.

> check-postgres-replication.rb

@sys-ops can you confirm replication is configured and running?

Also, @digiisoft @sys-ops please provide Ruby and PostgreSQL versions?

**Comment by phumpal** [comment] 2019-03-12 20:04
@majormoses should we improve the replication check to determine replication status prior to computing lag

Perhaps proceeding only when `select pg_is_in_recovery();` is true? 

Alternatively we could check state

```
select state from pg_stat_replication;
```

This probably requires a bit more thought and potentially a separate issue.

**Comment by sys-ops** [comment] 2019-03-12 21:34
Not sure if that would be enough:
```
    begin
      s_segment, s_offset = slave.split('/')
    rescue
      warning "Streaming replication is disabled or it has not yet started"
    end
```
If streaming replication is disabled, or if it has not yet started, the function returns NULL.
Actually, I would check if slave is NULL...
```
    if slave.nil?
      warning "Streaming replication is disabled or it has not yet started"
    end
```
@phumpal replication was not running (now it is), however it is good to handle such a problem in a proper way.
I will be happy to create a pull request.

**Comment by majormoses** [comment] 2019-03-13 01:22
> Perhaps proceeding only when `select pg_is_in_recovery();` is true?

I would lean towards having that be a critical scenario

> If streaming replication is disabled, or if it has not yet started, the function returns NULL.
Actually, I would check if slave is NULL...

I would say this should be a critical rather than a warning, if replication is not enabled or started then there is no point in doing anything with this check.

Since both of these are library methods rather than calling `critical` directly (which makes writing tests much harder) we should return a result with a status. For example:
```ruby
def foo(bar, baz)
  if safe_to_proceed?
    status, result_or_message
  else
    critical, "some_error_message"
end


thing = foo(bar, baz)
if thing[0] != 0
  critical thing[1]
else
  do_thing_with(thing[1])
end
```

That code is probably not actually copy/paste ready but it illustrates the idea.

**Comment by phumpal** [comment] 2019-03-13 04:08
@sys-ops your solution looks like a great start. I concur with @majormoses on how to proceed https://github.com/sensu-plugins/sensu-plugins-postgres/issues/70#issuecomment-472242879.

If you have the time a PR would be awesome!

**Comment by phumpal** [comment] 2019-05-01 22:23
@sys-ops I can take this if you don't have time.

**Comment by phumpal** [comment] 2020-01-17 07:14
@digiisoft @sys-ops can you try the latest release and see if the issue is fixed?

**Comment by phumpal** [comment] 2020-02-20 07:40
@majormoses any chance we can close this? I suspect this is now fixed.

**Comment by phumpal** [comment] 2020-02-26 19:51
Ping @majormoses /cc @digiisoft @sys-ops

**Closed as completed** 2020-02-26 22:14 UTC
